version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
      MYSQL_USER: ravi
      MYSQL_PASSWORD: mypassword
    ports:
      - "3300:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: . # Adjust this path if needed
    container_name: task-management
    depends_on:
      - mysql
    ports:
      - "8087:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task
      SPRING_DATASOURCE_USERNAME: ravi
      SPRING_DATASOURCE_PASSWORD: mypassword

  react-app:
    build: C:\Users\User\Desktop\Revature\ReactJs\task-management  # Path to your React Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"  # Map React app port to the host
    depends_on:
      - springboot-app

volumes:
  mysql-data:
