name: Spring demo GHA
#Trigger
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
#Jobs
jobs :
  build :
    runs-on: ubuntu-latest #Environment to run jobs

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build project
        run : mvn clean install
      - name: Test
        run : mvn test
        if: ${{ contains(github.event.head_commit.message, 'test commit') }}

      - name: Check Result
        run: |
          echo "event = ${{github.event_name}}"
          echo "Repository = ${{github.repository}}"
          echo "JOB ID=${{github.job}}"
          echo "RUN ID=${{github.run_id}}"
          echo "user = ${{github.actor}}"
          

      - name: Upload jar file
        if: ${{success()}}
        uses: actions/upload-artifact@v3
        with:
          name: myapp-jar
          path: target/*.jar
