name: Spring demo GHA
#Trigger
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
#Jobs
jobs :
  build :
    runs-on: ubuntu-latest #Environment to run jobs

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        run : mvn clean install
      - name: Test
        run : mvn test

      - name: upload jar file
        if: ${{success()}}
        uses: actions/upload-artifact@v 3
        with:
          name: myapp-jar
          path: target/*.jar
